### ISSUE TITLE
easiest way to upgrade

### ISSUE THREAD

**Issue by cirrusflyer** [gtxaspec/wz_mini_hacks#43]
Since I have SSH working, what's the easiest way to upgrade the camera to the latest version?  Thanks

EDIT - easiest as in "over the air" instead of pulling the card.  So by uploading files to replace existing ones.

**Comment by capncybo** [comment]
IMO this is an excellent question, I've been bouncing between this project with a decentralized (node-type) model (meaning each camera) has it's own separate config & setup. And testing the Centralized https://github.com/mrlt8/docker-wyze-bridge project.
BOTH projects are excellent & I've experienced rapid development & changes which are sometimes hard to keep current.
Currently the UPDATING advantage obviously goes to the Centralized model.
However if an "over the air - UPGRADE" could somehow be incorporated into this project...
It could eliminate the frequent need to remove/reinsert microSDCards which is MULTIPLIED by the total number of cameras.
Not to mention that some cameras may be located high-up, hidden away or even somewhat secured.
Just an idea/suggestion.
And thanks for your continued efforts

**Comment by cirrusflyer** [comment]
Just in case I'm not asking the right question.  Since we have SSH access and maybe SCP/SFTP, can we connect with our local PC and upload the latest files?  Real "Over the Air" wouldn't require connecting and copying files, but anything to make it easier now would be useful.

**Comment by virmaior** [comment]
I would think one could overwrite the current files from an extracted copy as long as one skips:
*authorized_keys
*run_mmc.sh
*swap

`scp -r wz_mini/SD_ROOT/ 192.168.10.10:/media/mmc/ 
`
at least one source claims scp can't exclude during recursive.

So perhaps:

`
rsync -rtz   --exclude={'wz_mini/run_mmc.sh','wz_mini/etc/ssh/authorized_keys'} --del --wz_mini/SD_ROOT/ 192.168.10.10:/media/mmc/ 

`

**Comment by gtxaspec** [comment]
run_mmc.sh has upgraded recently, make sure you backup your run_mmc.sh and just fill out the new one, just in case.  

most of the features for this project have been developed, so we shouldn't see so many big changes anymore...

**Comment by gtxaspec** [comment]
once I have v2 support squared away, I'll look into creating an easy upgrade mechanism.

**Comment by capncybo** [comment]
Your rapid rate of development is Greatly appreciated... but very hard to keep up with LOL.
I'm currently at work & itching to test your latest version (but have to wait).
Curious as to the advantage(s) of adding (secondary/tertiary) streams by changing the URL/PATH but using the same port???
Does it...
-Save CPU-Resources on the Camera
-Minimize network Bandwidth, or...
-Align more with existing IP-Camera Standards?
+
I'm trying to get my head around: RTSP-Unicast
At first I thought, maybe it only allows ONLY one connection at a time... NOPE (RTSP supports multiple decoder connections)
So then what's the primary rational for multiple streams hmmm
With simultaneous clients does each additional connection add latency ???

Googled  RTSP-Unicast vs  RTSP-Multicast...
Owww my frigg'n head

**Comment by gtxaspec** [comment]
its for some users who have software which only support rtsp substreams on the same url, otherwise no improvement

**Comment by capncybo** [comment]
I would have thought two streams on the same port would create more network packet congestion/collisions

**Comment by endertable** [comment]
Maybe someone can compile subversion (svn) for MIPS  https://archive.apache.org/dist/subversion/
Then it would be just a comparison of a ver.txt file within wz_mini and if it changes, then do a 'svn checkout" on the SD card.

Then it would probably be better to have all the variables within run_mmc.sh placed in a file "wz_mini_common" in the root of the SD Card and then sourced in by v3_init.sh and run_mmc.sh AFTER default variables (to allow for new changes).

I tried compiling svn so I could run some proof of concept but I am running a 32-bit Linux and everything wants a 64-bit  :(  
I will need to make that upgrade soon.

If anyone can compile it, I would be happy to do the testing..

**Comment by shamlord** [comment]
> I would have thought two streams on the same port would create more network packet congestion/collisions

IP packets do not work that way. 

IP addresses uniquely identify a network device, and port numbers are associated with the different applications running on that device.  Regardless of port number though, a network device (and IP address) cannot receive more than one packet at a time.  If the two network streams were on different ports, the packets would still be sequenced by the transmitter (the camera) so that they are sent one at a time, and received by your computer or NVR in the same way.

Why was this changed?  On IP cameras that offer both high and low resolution streams, most of them do so on the same port but using different URLs.  It is unusual for those streams to be offered on different ports.  Gtxaspec's project prevously offered the streams on two different ports, but I think that requires running two instances of the RTSP server on the camera.  Only one instance of the RTSP server is needed when transmitting both streams on a single port.  This should reduce the CPU load on the camera slightly, and is probably why this is the common implementation in other IP cameras.

Also for me personally, I use Blue Iris as my NVR, and it only supports high and low resolution streams on the same port, not different ports.  From the googling I've done, this also seems to be typical for NVRs.. though IIRC there are NVRs that support multiple streams on different ports from the same camera.

**Comment by shamlord** [comment]
Using SCP to update the files with this command:
```
\Desktop\SD_ROOT_4>scp -r * root@192.168.2.17:/media/mmc/
```
was partially successful, with the following errors:
```
scp: /media/mmc//wz_mini/bin/busybox: Text file busy
scp: /media/mmc//wz_mini/bin/dropbear: Text file busy
scp: /media/mmc//wz_mini/bin/scp: Text file busy
scp: /media/mmc//wz_mini/bin/v4l2rtspserver: Text file busy
```
Probably an upload of a zip file with a decompress on reboot will be necessary to ensure everything is updated.

**Comment by virmaior** [comment]
most recently I was thinking an optimal wz_mini_hacks update strategy would be:
1. scp the new version into a different directory wz_mini_LATEST 
2. add a check the startup script to check if there is a wz_mini_LATEST  and if one exists 
  1. Copy over settings in run_mmc.sh and authorized_keys to LATEST
  2. rename the current wz_mini to wz_mini_OLD and the LATEST to wz_mini
3. reboot

Main question is if busybox supports mv for directories

**Comment by endertable** [comment]
@virmaior Your rsync solution was very good AND efficient because it only copies over the files that have changed.   Of the 4 locked files mentioned above, I don't foresee dropbear and scp changing very often, but v4l2rtspserver and busybox may get more updates.

As run_mmc.sh also stores most parameters, including new ones, before you do a copy of the old file over the new one, rename the new one to run_mmc.sh_NEW and then check for differences, mostly parameters and function changes/additions.

**Comment by virmaior** [comment]
it'd be nice if the parameter setting was split out of run_mmc.sh but it's not that much work to compare a new version and an old version and manually copy them over.

**Comment by gtxaspec** [comment]
once I wrap up v2 support, the parameters will be split out of the script, so it will be much easier to upgrade and keep settings.

**Comment by gtxaspec** [comment]
latest release includes new `wz_mini.conf` config file, variables only.  run_mmc.sh is no more.

**Comment by endertable** [comment]
@gtxaspec fantastic work!!!  I don't know how you do it.  You're on top of the game!

Thanks for making Wyze Cams more useful!

**Comment by capncybo** [comment]
I second the compliment + with the addition of the https in wget...
Couldn't we basically, update via... something like:
cd /opt
wget https://github.com/gtxaspec/wz_mini_hacks/archive/refs/heads/master.zip
mv wz_mini_hacks wz_mini_hacks_old
unzip master.zip

Note: And copy the previous config into the new directory location
Top it all off with another move command to rename the directory & it's recursive components...
And it should be updated, right ???

**Comment by endertable** [comment]
You got it.  Basically, the update trail ended for him when he moved the params into their own file.  The only files you need to preserve are:  wz_mini/etc/ssh/authorized_keys and the new wz_mini.conf file.  Your mileage for the wget directly to the camera may vary as there are alot of processes running that may slow it down to a crawl, so the rsync would mostly be from your server to the cameras.  It is most efficient because it will only update/delete files that need to be vs the whole archive.  So using @virmaior method, it would be (from your server to the camera{s}, with IP 192.168.10.10 being a camera:

rsync -rtz --exclude={'wz_mini/etc/ssh/authorized_keys'} --del --wz_mini/SD_ROOT/ 192.168.10.10:/media/mmc/ 

The only manual intervention would be to see what new params were added to wz_mini.conf, if any, and edit the file on your server,

**Comment by shamlord** [comment]
Is there a decent, elegant rsync alternative that can be run from a windows machine? 

So far I've looked at:
Cygwin and Git offer copies of rsync, but that is an awful lot to install just for one utility, plus it seems they have a lot of configuration that needs to be done. "cwrsync" is another alternative but is also kind of hackish, requiring setting PATH environment variables or editing a batch file just to run. WinSCP looks like it could have fit the bill, but it doesn't support publickey authentication. There's a nice port of rclone for windows, but it is for cloud providers only and doesn't appear to support SCP.

It would be ideal if MS would just add rsync to the Windows Terminal app, which I've been using for its included copies SSH and SCP.  Barring that though, and until/unless I switch away from Blue Iris to something that runs on Linux, the sole device that will talk to my cameras will be a Windows machine.

**Comment by gtxaspec** [comment]
WSL, windows subsystem for linux, you could probably install it and use that ( never used it, but i hear its good )

**Comment by shamlord** [comment]
I appreciate the suggestion. I was trying to avoid that too unfortunately. I do have it on my windows desktop for goofing around though. 

My ideal use case would be to RDP into my windows NVR straddling my two networks to get at the cameras. It looks like I might have to just resort to connecting from my linux laptop to my camera wifi and handle it that way.

**Comment by shamlord** [comment]
I was wrong.. WinSCP does actually support public key authentication, configured as follows:

1. Launch WinSCP, click New Session.
2. Verify the site hostname, ip, and port are correct for the camera. Username root, password blank.
3. Click Advanced, under the SSH heading on the left, click Authentication. Select a private key in PuTTY's .PPK format.
(_Tools -> Generate will allow you to import an existing private key from SSH and save it in PPK format_)
4. Still in Advanced Settings, click SCP/Shell under Environment, and set the shell to: `/media/mmc/wz_mini/bin/bash`

After connecting to one of the camera "sessions", click Synchronize on the toolbar and set the desired options. The only issue I have currently is that GitHub's ZIP file option does not preserve file timestamps. Github Desktop doesn't seem to either. I guess don't compare timestamps?

**Comment by shamlord** [comment]
I use a different hostname for each camera, but the remaining settings are identical between cameras. I've not had luck assigning hostnames to the cameras via DHCP. 

I want to place the hostname in a separate config file or script, which I'll just leave on the camera during updates. If I added my own additional script to `/etc/init.d/`, would it be run automatically?  Or, if you think it's a good idea, maybe split that setting off to `hostname.conf`?

**Comment by gtxaspec** [comment]
latest version includes `/opt/wz_mini/usr/bin/upgrade-run.sh` which offers rudimentary upgrade support.  

it only backs up 2 files, `authorized_keys`, and `wz_mini.conf`, and restores them after the upgrade.  make sure you have space on your memory card!

**Comment by capncybo** [comment]
@gtxaspec Awesome-sauce!!! To Date: those are the only TWO files I've ever changed, so...
running: **upgrade-run.sh** Is totally fine by me ;-)
Yay... no more pulling the SD-Card!!!

**Comment by capncybo** [comment]
How we are supposed to **properly** initialize the upgrade process?  Do we...
- Enter: /opt/wz_mini/usr/bin/upgrade-run.sh  (And follow the prompts)
- Set: DISABLE_FW_UPGRADE="false" (Inside: wz_mini.conf) & simply reboot the camera 
- Or can it "already" be done either way
I ask this because when manually running the upgrade-run.sh script...
In the upgrade-logs some "running-files" could not be "immediately" replaced & the script did contain a reboot statement.
So from what I can tell...
I think you already have this working.
I just thought I'd ask if the DISABLE_FW_UPGRADE="false/true"
is ONLY for the WYZE Firmware, or does it also perform a [wz_mini_hacks] Upgrade?

**Comment by gtxaspec** [comment]
DISABLE_FW_UPGRADE="false/true"
is ONLY for the WYZE Firmware, is correct.  just run the upgrade script for now.

**Comment by gtxaspec** [comment]
flow:

run `/opt/wz_mini/usr/bin/upgrade-run.sh`
downloads latest master
backs up user configs
extracts the master archive and verifies file integrity
reboots the camera into special "upgrade mode"
upgrade mode has audio prompts so you know it's working (since most to not have serial access to the camera)
performs the upgrade and restores user config files
camera reboots again
you'll hear the initializing first boot audio prompt
back up and running.

**Comment by PanchitoSolo** [comment]
I know that upgrade script is in early stages, just giving a heads up here. 

> latest version out now includes `ENABLE_USB_ETH_MODULES=` in the config.

With this change https://github.com/gtxaspec/wz_mini_hacks/issues/39#issuecomment-1143147212 I noticed that this new config variable doesn't get added automatically when executing upgrade-run.sh into the restored wz_user.sh (I tried to use diff and patch with no success on my side for automatization), I think this can result in no default ethernet driver loaded by default losing internet connection for everyone that upgrades with script.

**Comment by capncybo** [comment]
I just tried to Upgrade a v3 camera (a few times) this morning via...
/opt/wz_mini/usr/bin/upgrade-run.sh

BUT...
md5sum: WARNING: 2 of 165 computed checksums did NOT match
Failure: archive has corrupted files

Not sure if anyone else is experiencing this ???

**Comment by capncybo** [comment]
Hmmm & now I cannot connect via SSH... I'm thinking perhaps my raspberry pi's SSH was changed or upgraded
As I've gotten the following...
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Failed to add the host to the list of known hosts (/home/pi/.ssh/known_hosts).
root@192.168.50.22: Permission denied (publickey).
But I did run:
ssh-keygen -f "/root/.ssh/known_hosts" -R "192.168.50.22"
which typically resolves my SSH connection

**Comment by gtxaspec** [comment]
there was an issue with the checksum file, it has been corrected now.  updates should work now.  

@capncybo not sure why your ssh doesn't work.  I would check the logs when you can.

**Comment by gtxaspec** [comment]
if this is working OK so far, which it has for me, I will move it into PATH and update the read me so everyone can use it

**Comment by capncybo** [comment]
LOL I was going to ask... if you would consider adding it to the path (As It's been working great for me as well).
So well in-fact... I just splurged & bought myself another 128G microSD card & mounted the camera back up-high.
I felt rather confident in doing so... as I haven't had to swap (in/out) any cards in quite some time.
Thanks to you (of course).

**Comment by capncybo** [comment]
Whoops (I must have jinxed it) as I just noticed something odd **after** upgrading my newest camera...
I had to manually run hostname (or perhaps a second reboot may have sufficed but perhaps, this behaviour is expected)

ssh root@192.168.50.21
COLUMNS=118;LINES=57;export COLUMNS LINES;
[root@WCV3:~]# hostname
FRONT-DOOR
[root@FRONT-DOOR:~]

**Comment by tavicu** [comment]
Hei. Awesome script. But can we have an option to add a parameter and skip the y/n input?

I would want to run a command (pssh) that run the script an all cameras. And with pssh you cannot interact with the command. It just run the command on all devices and print the output (if you want).

**Comment by gtxaspec** [comment]
I like that.  I've been using ansible to work on batches of cameras.  I'll look into it.

**Comment by gtxaspec** [comment]
latest release includes `unattended` option for upgrade script, no prompts:

`upgrade-run.sh unattended`

**Comment by gtxaspec** [comment]
upgrade-script is available in PATH now, closing issue.
